import type { Shop } from "./types";

// export const mockProducts: Product[] = [
//   {
//     id: "1",
//     name: "Premium Coffee Beans",
//     barcode: "1234567890123",
//     brand: "Nescafe",
//     salePriceUSD: 12.99,
//     costPriceUSD: 8.5,
//     currentStock: 45,
//     minStockAlert: 10,
//     category: "Beverages",
//     subcategory: "Coffee",
//   },
//   {
//     id: "2",
//     name: "Organic Olive Oil",
//     barcode: "2345678901234",
//     brand: "Al Arz",
//     salePriceUSD: 18.5,
//     costPriceUSD: 12.0,
//     currentStock: 3,
//     minStockAlert: 5,
//     category: "Food",
//     subcategory: "Oils",
//     expiryDate: "2026-06-15",
//   },
//   {
//     id: "3",
//     name: "Wireless Earbuds",
//     barcode: "3456789012345",
//     brand: "JBL",
//     salePriceUSD: 29.99,
//     costPriceUSD: 18.0,
//     currentStock: 12,
//     minStockAlert: 3,
//     category: "Electronics",
//     subcategory: "Audio",
//   },
//   {
//     id: "4",
//     name: "Natural Honey",
//     barcode: "4567890123456",
//     brand: "Lebanese Farms",
//     salePriceUSD: 8.75,
//     costPriceUSD: 5.0,
//     currentStock: 0,
//     minStockAlert: 5,
//     category: "Food",
//     subcategory: "Sweeteners",
//     expiryDate: "2027-01-20",
//   },
//   {
//     id: "5",
//     name: "Leather Wallet",
//     barcode: "5678901234567",
//     brand: "Tommy Hilfiger",
//     salePriceUSD: 35.0,
//     costPriceUSD: 20.0,
//     discountType: "percentage",
//     discountValue: 10,
//     currentStock: 8,
//     minStockAlert: 2,
//     category: "Accessories",
//     subcategory: "Wallets",
//   },
//   {
//     id: "6",
//     name: "Herbal Tea Set",
//     barcode: "6789012345678",
//     brand: "Lipton",
//     salePriceUSD: 15.25,
//     costPriceUSD: 9.0,
//     currentStock: 22,
//     minStockAlert: 8,
//     category: "Beverages",
//     subcategory: "Tea",
//     expiryDate: "2026-09-10",
//   },
//   {
//     id: "7",
//     name: "USB-C Charger",
//     barcode: "7890123456789",
//     brand: "Anker",
//     salePriceUSD: 19.99,
//     costPriceUSD: 10.0,
//     currentStock: 5,
//     minStockAlert: 5,
//     category: "Electronics",
//     subcategory: "Chargers",
//   },
//   {
//     id: "8",
//     name: "Scented Candle",
//     barcode: "8901234567890",
//     brand: "Yankee",
//     salePriceUSD: 11.5,
//     costPriceUSD: 6.0,
//     discountType: "fixed",
//     discountValue: 1.5,
//     currentStock: 30,
//     minStockAlert: 10,
//     category: "Home",
//     subcategory: "Decor",
//   },
// ]

export const mockShops: Shop[] = [
  {
    id: "1",
    name: "Al Nour Market",
    owner: "Ahmad Hassan",
    email: "ahmad@alnour.com",
    subscriptionExpiry: "2026-03-15",
    status: "active",
    productsCount: 156,
    salesThisMonth: 2450,
  },
  {
    id: "2",
    name: "Beirut Electronics",
    owner: "Sarah Khoury",
    email: "sarah@beirutelec.com",
    subscriptionExpiry: "2026-01-28",
    status: "active",
    productsCount: 89,
    salesThisMonth: 5200,
  },
  {
    id: "3",
    name: "Cedar Grocery",
    owner: "Michel Aoun",
    email: "michel@cedargrocery.com",
    subscriptionExpiry: "2025-12-01",
    status: "suspended",
    productsCount: 234,
    salesThisMonth: 0,
  },
  {
    id: "4",
    name: "Tripoli Fashion",
    owner: "Layla Mahmoud",
    email: "layla@tripolifashion.com",
    subscriptionExpiry: "2026-06-20",
    status: "active",
    productsCount: 412,
    salesThisMonth: 8900,
  },
  {
    id: "5",
    name: "Sidon Hardware",
    owner: "Karim Nassar",
    email: "karim@sidonhw.com",
    subscriptionExpiry: "2026-02-10",
    status: "active",
    productsCount: 567,
    salesThisMonth: 3100,
  },
]

export const categories = [
  {
    name: "Beverages",
    subcategories: ["Coffee", "Tea", "Soft Drinks", "Juice", "Water"],
  },
  {
    name: "Food",
    subcategories: ["Oils", "Sweeteners", "Snacks", "Canned Goods", "Dairy"],
  },
  {
    name: "Electronics",
    subcategories: ["Audio", "Chargers", "Cables", "Accessories"],
  },
  {
    name: "Accessories",
    subcategories: ["Wallets", "Bags", "Belts", "Watches"],
  },
  {
    name: "Home",
    subcategories: ["Decor", "Kitchen", "Bathroom", "Cleaning"],
  },
  {
    name: "Other",
    subcategories: ["Miscellaneous"],
  },
]

export const brands = [
  "Nescafe",
  "Lipton",
  "Al Arz",
  "Lebanese Farms",
  "JBL",
  "Anker",
  "Tommy Hilfiger",
  "Yankee",
  "Sony",
  "Samsung",
  "Apple",
  "Other",
]

export const DEFAULT_EXCHANGE_RATE = 89500
