import type { Product, Shop } from "./types";

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Premium Coffee Beans",
    barcode: "1234567890123",
    brand: "Nescafe",
    priceUSD: 12.99,
    costUSD: 8.5,
    stock: 45,
    minStockAlert: 10,
    category: "Beverages",
    subcategory: "Coffee",
  },
  {
    id: "2",
    name: "Organic Olive Oil",
    barcode: "2345678901234",
    brand: "Al Arz",
    priceUSD: 18.5,
    costUSD: 12.0,
    stock: 3,
    minStockAlert: 5,
    category: "Food",
    subcategory: "Oils",
    expiryDate: "2026-06-15",
  },
  {
    id: "3",
    name: "Wireless Earbuds",
    barcode: "3456789012345",
    brand: "JBL",
    priceUSD: 29.99,
    costUSD: 18.0,
    stock: 12,
    minStockAlert: 3,
    category: "Electronics",
    subcategory: "Audio",
  },
  {
    id: "4",
    name: "Natural Honey",
    barcode: "4567890123456",
    brand: "Lebanese Farms",
    priceUSD: 8.75,
    costUSD: 5.0,
    stock: 0,
    minStockAlert: 5,
    category: "Food",
    subcategory: "Sweeteners",
    expiryDate: "2027-01-20",
  },
  {
    id: "5",
    name: "Leather Wallet",
    barcode: "5678901234567",
    brand: "Tommy Hilfiger",
    priceUSD: 35.0,
    costUSD: 20.0,
    discountType: "percentage",
    discountValue: 10,
    stock: 8,
    minStockAlert: 2,
    category: "Accessories",
    subcategory: "Wallets",
  },
  {
    id: "6",
    name: "Herbal Tea Set",
    barcode: "6789012345678",
    brand: "Lipton",
    priceUSD: 15.25,
    costUSD: 9.0,
    stock: 22,
    minStockAlert: 8,
    category: "Beverages",
    subcategory: "Tea",
    expiryDate: "2026-09-10",
  },
  {
    id: "7",
    name: "USB-C Charger",
    barcode: "7890123456789",
    brand: "Anker",
    priceUSD: 19.99,
    costUSD: 10.0,
    stock: 5,
    minStockAlert: 5,
    category: "Electronics",
    subcategory: "Chargers",
  },
  {
    id: "8",
    name: "Scented Candle",
    barcode: "8901234567890",
    brand: "Yankee",
    priceUSD: 11.5,
    costUSD: 6.0,
    discountType: "fixed",
    discountValue: 1.5,
    stock: 30,
    minStockAlert: 10,
    category: "Home",
    subcategory: "Decor",
  },
]

export const mockShops: Shop[] = [
  {
    id: "1",
    name: "Al Nour Market",
    owner: "Ahmad Hassan",
    email: "ahmad@alnour.com",
    subscriptionExpiry: "2026-03-15",
    status: "active",
    productsCount: 156,
    salesThisMonth: 2450,
  },
  {
    id: "2",
    name: "Beirut Electronics",
    owner: "Sarah Khoury",
    email: "sarah@beirutelec.com",
    subscriptionExpiry: "2026-01-28",
    status: "active",
    productsCount: 89,
    salesThisMonth: 5200,
  },
  {
    id: "3",
    name: "Cedar Grocery",
    owner: "Michel Aoun",
    email: "michel@cedargrocery.com",
    subscriptionExpiry: "2025-12-01",
    status: "suspended",
    productsCount: 234,
    salesThisMonth: 0,
  },
  {
    id: "4",
    name: "Tripoli Fashion",
    owner: "Layla Mahmoud",
    email: "layla@tripolifashion.com",
    subscriptionExpiry: "2026-06-20",
    status: "active",
    productsCount: 412,
    salesThisMonth: 8900,
  },
  {
    id: "5",
    name: "Sidon Hardware",
    owner: "Karim Nassar",
    email: "karim@sidonhw.com",
    subscriptionExpiry: "2026-02-10",
    status: "active",
    productsCount: 567,
    salesThisMonth: 3100,
  },
]

export const categories = [
  {
    name: "Beverages",
    subcategories: ["Coffee", "Tea", "Soft Drinks", "Juice", "Water"],
  },
  {
    name: "Food",
    subcategories: ["Oils", "Sweeteners", "Snacks", "Canned Goods", "Dairy"],
  },
  {
    name: "Electronics",
    subcategories: ["Audio", "Chargers", "Cables", "Accessories"],
  },
  {
    name: "Accessories",
    subcategories: ["Wallets", "Bags", "Belts", "Watches"],
  },
  {
    name: "Home",
    subcategories: ["Decor", "Kitchen", "Bathroom", "Cleaning"],
  },
  {
    name: "Other",
    subcategories: ["Miscellaneous"],
  },
]

export const brands = [
  "Nescafe",
  "Lipton",
  "Al Arz",
  "Lebanese Farms",
  "JBL",
  "Anker",
  "Tommy Hilfiger",
  "Yankee",
  "Sony",
  "Samsung",
  "Apple",
  "Other",
]

export const DEFAULT_EXCHANGE_RATE = 89500
